# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"simrecorder": "pyfly_fixed_wing_visualizer.ipynb"}

modules = ["pyfly_fixed_wing_visualizer.py"]

doc_url = "https://0pss.github.io/pyfly_fixed_wing_visualizer/"

git_url = "https://github.com/0pss/pyfly_fixed_wing_visualizer/tree/master/"

def custom_doc_links(name): return None
